spring:
  application:
    name: kafka-async-producer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kafka_project?rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9094
      - localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      properties:
        linger.ms: 0   # 지연시간 최소화가 목적 → 배치 대기 없이 즉시 전송
